app/models.py
from app import db
from werkzeug.security import generate_password_hash,check_password_hash 
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'



    id = db.Column(db.Integer,primary_key = True)
    username =db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch', backref = 'user',lazy = "dynamic")
    comments = db.relationship("Comment", backref="user", lazy = "dynamic")

    def save_user(self):
        db.session.add(self)
        db.session.commit()


    @property

    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def get_user_pitches(self):
        user = User.query.filter_by(id = self.id).first()
        return user.pitches

    def get_user_comments(self):
        user = User.query.filter_by(id = self.id).first()
        return user.comments

        
    def __repr__(self):
        return f'User {self.username}'
        
class Pitch(db.Model):

    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key= True)
    content = db.Column(db.String)
    title = db.Column(db.String)
    date = db.Column(db.String)
    time = db.Column(db.String)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments = db.relationship("Comment", backref = "pitch", lazy = "dynamic")
    category = db.Column(db.String)

    
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch(cls,id):
        pitches = Pitch.query.filter_by(pitch_id=id).first()
        comments = Comment.query.filter_by(pitch_id = pitch.id).order_by(Comment.time.desc())
        return pitches 

class Comment(db.Model):
    
    __tablename__= "comments"

    id = db.Column(db.Integer,primary_key = True)
    content = db.Column(db.String)
    date = db.Column(db.String)
    time = db.Column(db.String)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch_id = db.Column(db.Integer,db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.ass(self)
        db.session.commmit()

def init_db():
    db.create_all()


    db.session.commit()

if __name__ == '__main__':
    init_db()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SelectField,SubmitField
from wtforms.validators import Required

class PitchForm(FlaskForm):

    pitch = TextAreaField('Your Pitch', validators=[Required()])
    # categories = SelectField(
    #     'Category',
    #     choices=[('pickup,pickup'),('interview,interview'),('product,product'),('promotion,promotion')]
    # )
    submit = SubmitField('submit')
    

class Comment(FlaskForm):
    content = TextAreaField("Add Comment")
    submit = SubmitField("Add")

class Updateprofile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask_sqlalchemy import SQLAlchemy 
from flask import Flask 
from config import config_options
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
bootstrap = Bootstrap()


def create_app(config_name):
  app = Flask(__name__)

  app.config.from_object(config_options[config_name])
 
  mail.init_app(app)
  configure_uploads(app,photos)
  bootstrap.init_app(app)
  db.init_app(app)
  login_manager.init_app(app)
  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
  
  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)

  return app

  

app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views,errors

app/main/views.py
from .forms import Updateprofile,PitchForm,Comment
from flask_login import login_required,current_user
from flask import render_template,request,redirect,url_for,abort
from ..models import User,Pitch,Comment
from .. import db,photos
from . import main 
import datetime





@main.route('/')
def index():

  '''
  View root page function that returns the index page and its data
  '''
  pitches = Pitch.query.all()
  title = "60sec pitch"
  return render_template('index.html', title = title, pitches = pitches)
# @main.route('/pitch/pitch/new/<int:id>') # , methods = ['GET','POST'])
# @login_required
# def new_pitch(id):


@main.route('/user/<uname>')
def profile(uname):
  user = User.query.filter_by(username = uname).first()
#   pitches = Pitch.query.filter_by(username = uname).order_by(Pitch.time.desc())
  title = user.username.upper()
  if user is None:
      abort(404)

  return render_template("profile/profile.html",user = user, title = title)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    
    
    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)



@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    title = "Edit Profile"
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))


@main.route("/pitches/<category>")
def categories(category):
    pitches = None
    if category == "all":
        pitches = Pitch.query.order_by(Pitch.time.desc())

    else:
        pitches = Pitch.query.filter_by(category = category).order_by(Pitch.time.desc()).all()


    return render_template("pitch.html",pitches = pitches)

       

@main.route('/<uname>/new/pitch', methods = ['GET','POST'])
@login_required
def new_pitch(uname):
    form = PitchForm()
    user = User.query.filter_by(username = uname).first()
    
    

    if form.validate_on_submit():
        
        pitch = form.pitch.data
        # category = form.categories.data
        originalDate = datetime.datetime.now()
        time = str(originalDate.time())
        time =time[0:5]
        date = str(originalDate)
        date = date[0:10]
        new_pitch= Pitch( content = pitch,user_id = user.id,time = time, date = date)

        new_pitch.save_pitch()
        pitches = Pitch.query.all()
        # return redirect(url_for("main.categories"))

    #",new_form = form)
    return render_template("new_pitch.html", new_form = form)

@main.route("/<pitch_id>/comments")
@login_required
def view_comments(pitch_id):
    pitch = Pitch.query.filter_by(id = pitch_id).first()
    title = "Comments"
    comments = pitch.get_pitch_comments()

    return render_template("view_comments.html",comments = comments, pitch = pitch, title = title)

@main.route("/<user>/pitch/<pitch_id>/new/comment", methods = ["GET","POST"])
@login_required
def comment(user,pitch_id):
    user = User.query.filter_by(id = user ).first()
    pitch = Pitch.query.filter_by(id = pitch_id).first()
    form = AddComment()
    title = "Add Comment"
    if form.validate_on_submit():
        content = form.content.data
        originalDate = datetime.datetime.now()
        time = str(originalDate.time())
        time = time[0:5]
        date = str(originalDate)
        date = date[0:10]
        new_comment = Comment(content = content, user = user, pitch = pitch)
        new_comment.save_comment()
        return redirect(url_for("main.comments", pitch_id= pitch.id))
    return render_template("comment.html,title = pitch.title,form = form, pitch = pitch ")

# @main.route('/pitch/<int:id>')
# def single_pitch(id):
#     pitch=Pitch.query.get(id)
#     if pitch is None:
#         abort(404)
#     
#     return render_template('pitch.html',pitch = pitch,format_pitch=formart_pitch)
    

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
  {% include "navbar.html" %}
{% endblock %}

app/templates/comment.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
  <h3>Comment on {{pitch.title | upper}} by {{pitch.user. username}}</h3>
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/comments.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row comment-row">
        <h3 class="comment-title">Comments for <strong>{{pitch.title | upper }}</strong> by <strong>{{pitch.user.name | upper}}</strong></h3>
        <a class="pitch-comment" href="{{url_for('main.comment',user = current_user.id, pitch_id = pitch.id)}}"><button class="btn btn-info mr-0">Add
                comment</button></a>


    </div>

        {% if comments %}
            {%for comment in comments%}
            <div class="row">
                <div class="col-xs-1 col-md-1 col-lg-1">
                    <img src="{{url_for('static', filename=comment.user.profile_pic)}}" class="img-thumbnail d-inline" height="60px" width="60px">
                </div>
                <div class="col">
                    <p class="d-inline"><a href="{{url_for('main.user',user_id=comment.user.id)}}"><strong>{{comment.user.username | upper}}</strong></a>: " {{comment.content}} "</p>
                    <p>Posted on <strong>{{comment.date}}</strong> at <strong>{{comment.time}}</strong></p>
                </div>
            </div>
            <hr>    
            {% endfor %}
        {% else %}
        <h2>There are no comments</h2>
        {% endif %}

    </div>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}


{% block content %}
<div class="body">
    <div class="container-fluid">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
    <div class="jumbotron">
        <h1 class="text-center animated lightSpeedIn delay-0.4s">Welcome to 60sec Pitch</h1>
        <h2 class="text-center">Categories</h2>
    </div>
    
        <div class="row">
          
              <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3"> 
                <div class="card">
                  <button><a href="{{url_for('main.categories',category='product')}}">Pickup lines</a></button>
              </div>
     
          </div>
          
              <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <div class="card">
                  <button><a href="{{url_for('main.categories',category='promotion')}}">Interview Pitch</a></button>
               </div>
          </div>
          
              <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <div class="card">
                  <button><a href="{{url_for('main.categories',category='pick-up')}}">Product Pitch</a></button>
              </div>
          </div> 
            <div class="cards">
              <div class="category col-xs-12 col-sm-12 col-md-3 col-lg-3">
                  <button><a href="{{url_for('main.categories',category='funny')}}">Promotion Pitch</a></button>
              </div>
            </div>
           
        </div>
        
    </div>
</div>
{% endblock %}

<style>
.body{
    background-color: bisque;
}


</style>

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Pitch </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/">Home</a>
                </li>
            </ul>   
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                <li><a href="{{url_for('main.new_pitch',uname = current_user.username)}}">New Pitch</a></li> 
            {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
        </ul>

    </div>
</div>

app/templates/new_pitch.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}


{% block content%}
<div class="container">
    {{wtf.quick_form(new_form) }}
    
</div>
{% endblock %}

app/templates/pitch.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    <h1 class="text-center">{{title | upper}} PITCHES</h1>
        {% if pitches %}
            {% for row in pitches | batch(3) %}
            <div class="row pitch-row">
                {% for pitch in row %}
                <div class="col-md-5 pitch-card">
                    <h3 class="source-name">{{pitch.title | upper}}</h3>
                    <p>Posted by <a href="{{url_for('main.user',user_id = pitch.user.id)}}"><strong>{{pitch.user.username}}</strong></a></p>
                    <p>Date: <strong>{{pitch.date}}</strong> at <strong>{{pitch.time}}</strong></p>
                    <p>"{{pitch.content}}"</p>
                    <p>CATEGORY: <strong>{{pitch.category | upper}}</strong></p>
                    <div class="extras">
                        <div>
                            {% if current_user.is_authenticated %}
                            <a class="pitch-comment" href="{{url_for('main.view_comments',pitch_id = pitch.id)}}">View Comments</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div> 
            {% endfor %}
        {% else %}
        <h2>You have no pitch yet</h2>
            <h4>Add Your Pitch</h4>
            <!-- </button> -->
            <div class="container">
                {{wtf.quick_form(new_form) }}
                
            </div>
        {% endif %}
    </div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html%}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h3>{{user.username| capitalize}}</h3>

      {% if user.bio %}
      <p>{{user.bio}}</p>
      {{%else%}}
      <p>
        {{user.username| capitalize}} has no bio
      </p>
      {%endif%}
    </div>
    
    {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}
    
    
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/view_comments.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row comment-row">
        <h3 class="comment-title">Comments for <strong>{{pitch.title | upper }}</strong> by <strong>{{pitch.user.name | upper}}</strong></h3>
        <a class="pitch-comment" href="{{url_for('main.comment',user = current_user.id, pitch_id = pitch.id)}}"><button class="btn btn-info mr-0">Add
                comment</button></a>


    </div>

        {% if comments %}
            {%for comment in comments%}
            <div class="row">
                <div class="col-xs-1 col-md-1 col-lg-1">
                    <img src="{{url_for('static', filename=comment.user.profile_pic)}}" class="img-thumbnail d-inline" height="60px" width="60px">
                </div>
                <div class="col">
                    <p class="d-inline"><a href="{{url_for('main.user',user_id=comment.user.id)}}"><strong>{{comment.user.username | upper}}</strong></a>: " {{comment.content}} "</p>
                    <p>Posted on <strong>{{comment.date}}</strong> at <strong>{{comment.time}}</strong></p>
                </div>
            </div>
            <hr>    
            {% endfor %}
        {% else %}
        <h2>There are no comments</h2>
        {% endif %}

    </div>

{% endblock %}